# Generated by Django 3.2 on 2022-07-20 10:40

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('created_at_gregory', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at_gregory', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('title', models.CharField(max_length=350, verbose_name='عنوان')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True, verbose_name='ادرس')),
                ('thumbnail_image', models.ImageField(upload_to='uploads/category/thumbnail_images', verbose_name='تصویر')),
                ('thumbnail_alt', models.CharField(blank=True, max_length=350, verbose_name='عنوان تصویر')),
                ('is_publisher', models.BooleanField(default=False, verbose_name='منتشر شده/نشده')),
                ('meta_title', models.CharField(max_length=350)),
                ('meta_description', models.TextField()),
                ('canonical_check', models.BooleanField(default=False)),
                ('canonical_url', models.URLField(default='')),
                ('schema_json', models.JSONField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='blog.blogcategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('created_at_gregory', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at_gregory', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('title', models.CharField(max_length=350, verbose_name='عنوان')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True, verbose_name='ادرس')),
                ('thumbnail_image', models.ImageField(upload_to='uploads/category/thumbnail_images', verbose_name='تصویر')),
                ('thumbnail_alt', models.CharField(blank=True, max_length=350, verbose_name='عنوان تصویر')),
                ('is_publisher', models.BooleanField(default=False, verbose_name='منتشر شده/نشده')),
                ('meta_title', models.CharField(max_length=350)),
                ('meta_description', models.TextField()),
                ('canonical_check', models.BooleanField(default=False)),
                ('canonical_url', models.URLField(default='')),
                ('schema_json', models.JSONField()),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='blog.blogtag', verbose_name='برچسب')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('created_at_gregory', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at_gregory', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('meta_title', models.CharField(max_length=350)),
                ('meta_description', models.TextField()),
                ('canonical_check', models.BooleanField(default=False)),
                ('canonical_url', models.URLField(default='')),
                ('schema_json', models.JSONField()),
                ('title', models.CharField(max_length=350, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True, verbose_name='ادرس')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='محتوا')),
                ('thumbnail_image', models.ImageField(upload_to='uploads/posts/thumbnail_images', verbose_name='تصویر')),
                ('thumbnail_alt', models.CharField(blank=True, max_length=350, verbose_name='عنوان تصویر')),
                ('status', models.CharField(choices=[('D', 'Draft'), ('P', 'Publish')], default='D', max_length=1, verbose_name='وضعیت')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.blogcategory', verbose_name='دسته بندی')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.blogtag', verbose_name='برچسب')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
    ]
