# Generated by Django 3.2 on 2022-07-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail_alt',
            field=models.CharField(blank=True, max_length=350, verbose_name='عنوان تصویر'),
        ),
    ]
