# Generated by Django 3.2 on 2022-07-22 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220720_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcategory',
            old_name='category',
            new_name='sub_category',
        ),
        migrations.RenameField(
            model_name='blogtag',
            old_name='tag',
            new_name='sub_tag',
        ),
    ]
