# Generated by Django 3.2 on 2022-07-20 10:40

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('created_at_gregory', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at_gregory', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('meta_title', models.CharField(max_length=350)),
                ('meta_description', models.TextField()),
                ('canonical_check', models.BooleanField(default=False)),
                ('canonical_url', models.URLField(default='')),
                ('schema_json', models.JSONField()),
                ('title', models.CharField(max_length=350, verbose_name='عنوان')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True, verbose_name='ادرس')),
                ('thumbnail_image', models.ImageField(upload_to='uploads/pages/thumbnail_images', verbose_name='تصویر')),
                ('thumbnail_alt', models.CharField(blank=True, max_length=350, verbose_name='عنوان تصویر')),
                ('is_publisher', models.BooleanField(default=False, verbose_name='منتشر شده/نشده')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
    ]
